services:
  gateway:
    build:
      context: /mnt/c/Users/lenio.prado/Documents/otimizador/services
      dockerfile: /mnt/c/Users/lenio.prado/Documents/docker-environments/dot-net-environment/docker-files/gateway-Dockerfile
    container_name: gateway
    ports:
      - "7000:7000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always